spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  jdbc:mysql://{mysql host}:{mysql port}/{database}
#    url: jdbc:mysql://10.22.4.160:3306/sonic?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
    url: jdbc:mysql://${MYSQL_HOST:10.22.4.160}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
#    url: jdbc:mysql://${MYSQL_HOST:10.22.4.160}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT&useSSL=false
    # mysql username
    username: root
    # mysql password
    password: root
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:data.sql

mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

actable:
  model:
    pack: org.cloud.sonic.controller.models.domain
  table:
    auto: update
  database:
    type: mysql

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: org.cloud.sonic.common.model