server:
  port: 0

spring:
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

# IP address of the gateway 网关的IP地址
gateway:
#  host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3000}/server
#  host: http://${SONIC_SERVER_HOST:192.168.132.164}:${SONIC_SERVER_PORT:3000}/server
#  host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3000}/server
  host: http://${SONIC_SERVER_HOST:10.22.4.160}:${SONIC_SERVER_PORT:3000}/server